import os
import csv
import argparse
import re
import math

path ='tmp/'

ok = True
a1 = "'"
a2 = "}"
a0 = "{"

output_file = 'aladin_SolarSystem.html'
open(output_file, 'w').close()
with open(output_file, 'w') as of:
   of.write('<HTML style="background-color:#ffffff">\n')
   of.write('<style>\n')
   of.write('sm {\n')
   of.write('  font-size: 10px;\n')
   of.write(' }\n')
   of.write('.title {\n')
   of.write('  font-size: 13px;\n')
   of.write(' }\n')
   of.write('body {\n')
   of.write(' font-family: Tahoma, sans-serif;\n')
   of.write(' margin:0;\n')
   of.write(' padding:0;\n')
   of.write('}\n')
   of.write('#custom-logo {\n')
   of.write('   position: relative;\n')
   of.write('   top: 162px;\n')
   of.write('   left: 2px;\n')
   of.write('   width: 36px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('#custom-logo2 {\n')
   of.write('   position: fixed;\n')
   of.write('   top: 15px;\n')
   of.write('   left: 92%;\n')
   of.write('   width: 50px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('#custom-logo3 {\n')
   of.write('   position: fixed;\n')
   of.write('   top: 200px;\n')
   of.write('   left: 2px;\n')
   of.write('   width: 43px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('/* Modal Styling */\n')
   of.write('.modal {\n')
   of.write('   display: none;\n')
   of.write('   position: fixed;\n')
   of.write('   top: 0;\n')
   of.write('   left: 0;\n')
   of.write('   width: 80%;\n')
   of.write('   height: 96%;\n')
   of.write('   background: rgba(0, 0, 0, 0.5);\n')
   of.write('   justify-content: center;\n')
   of.write('   align-items: center;\n')
   of.write('   z-index: 1000;\n')
   of.write('   }\n')
   of.write('.modal-content {\n')
   of.write('      background: white;\n')
   of.write('      padding: 0;\n')
   of.write('      border-radius: 8px;\n')
   of.write('      width: 85%;\n')
   of.write('      height: 80%;\n')
   of.write('      max-width: 900px;\n')
   of.write('      max-height: 600px;\n')
   of.write('      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n')
   of.write('      display: flex;\n')
   of.write('      flex-direction: column;\n')
   of.write('}\n')
   of.write('.close-btn {\n')
   of.write('      align-self: flex-end;\n')
   of.write('      cursor: pointer;\n')
   of.write('      font-size: 24px;\n')
   of.write('      margin: 10px;\n')
   of.write('}\n')
   of.write('.close-btn3 {\n')
   of.write('     align-self: flex-end;\n')
   of.write('     cursor: pointer;\n')
   of.write('     font-size: 24px;\n')
   of.write('     margin: 10px;\n')
   of.write('}\n')
   of.write('iframe {\n')
   of.write('      flex: 1;\n')
   of.write('      border: none;\n')
   of.write('      border-radius: 0 0 8px 8px;\n')
   of.write('}\n')
   of.write('    body {\n')
   of.write("      font-family: 'Helvetica', sans-serif;\n")
   of.write('    }\n')
   of.write('</style>\n')
   of.write('<HEAD>\n')
   of.write('   <script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js" charset="utf-8"></script>\n')
   of.write('   <script type="text/javascript">var jqMenu = jQuery.noConflict();</script>\n')
   of.write('   <script type="text/javascript">\n')
   of.write('   var hipsDir=null;</script>\n')
   of.write('</HEAD>\n')
   of.write('<script>\n')
   of.write('let object = null;\n')
   of.write('let lat = null;\n')
   of.write('let long = null;\n')
   of.write('let SolarSystemObject = null;\n')
   of.write('window.onload = () => {\n')
   of.write('  const urlParams = new URLSearchParams(window.location.search);\n')
   of.write("  object = urlParams.get('object') || 'Earth';  \n")
   of.write('  const urlParamsla = new URLSearchParams(window.location.search);\n')
   of.write("  lat = urlParamsla.get('lat') || '0.0';  \n")
   of.write('  const urlParamslo = new URLSearchParams(window.location.search);\n')
   of.write("  long = urlParamslo.get('long') || '0.0';  \n")
   of.write('  if (object == "Moon") {\n')
   of.write('    document.getElementById("Moon").checked = true;\n')
   of.write('    SolarSystemObject = "Moon";\n')
   of.write('  } else if (object == "Mars") {\n')
   of.write('    document.getElementById("Mars").checked = true;\n')
   of.write('    SolarSystemObject = "P/Mars/MOLA-color";\n')
   of.write('  } else if (object == "Venus") {\n')
   of.write('    document.getElementById("Venus").checked = true;\n')
   of.write('    SolarSystemObject = "P/Venus/Magellan/Topography-4641m";\n')
   of.write('  } else if (object == "Sun") {\n')
   of.write('    document.getElementById("Sun").checked = true;\n')
   of.write('    SolarSystemObject = "CDS/P/Sun/euvi-aia304-2012";\n')
   of.write('  } else if (object == "Ceres") {\n')
   of.write('    document.getElementById("Ceres").checked = true;\n')
   of.write('    SolarSystemObject = "IAPS_P_Ceres_Dawn_FC-CE-LAMO-CLR";\n')
   of.write('  } else if (object == "Jupiter") {\n')
   of.write('    document.getElementById("Jupiter").checked = true;\n')
   of.write('    SolarSystemObject = "P/Jupiter/PIA07782";\n')
   of.write('  } else if (object == "Mercury") {\n')
   of.write('    document.getElementById("Mercury").checked = true;\n')
   of.write('    SolarSystemObject = "P/Mercury/MESSENGER-MDIS-LOI-166m";\n')
   of.write('  } else if (object == "Neptune") {\n')
   of.write('    document.getElementById("Neptune").checked = true;\n')
   of.write('    SolarSystemObject = "P/Neptune/Voyager2";\n')
   of.write('  } else if (object == "Pluto") {\n')
   of.write('    document.getElementById("Pluto").checked = true;\n')
   of.write('    SolarSystemObject = "P/Pluto/NewHorizons-Jul2017-300m";\n')
   of.write('  } else if (object == "Ganymede") {\n')
   of.write('    document.getElementById("Ganymede").checked = true;\n')
   of.write('    SolarSystemObject = "P/Ganymede/VoyagerGalileo-SSI-1km";\n')
   of.write('  } else if (object == "Tethys") {\n')
   of.write('    document.getElementById("Tethys").checked = true;\n')
   of.write('    SolarSystemObject = "P/Tethys/Cassini-PIA18439";\n')
   of.write('  } else if (object == "Titania") {\n')
   of.write('    document.getElementById("Titania").checked = true;\n')
   of.write('    SolarSystemObject = "P/Titania/Voyager";\n')
   of.write('  } else if (object == "Triton") {\n')
   of.write('    document.getElementById("Triton").checked = true;\n')
   of.write('    SolarSystemObject = "P/Triton/Voyager2-600m";\n')
   of.write('  } else if (object == "Charon") {\n')
   of.write('    document.getElementById("Charon").checked = true;\n')
   of.write('    SolarSystemObject = "P/Charon/NewHorizon-PIA19866";\n')
   of.write('  } else if (object == "Earth") {\n')
   of.write('    document.getElementById("Earth").checked = true;\n')
   of.write('    SolarSystemObject = "P/Earth/BlueMarble";\n')
   of.write('  } else {\n')
   of.write('    alert("Data for object " + object + " not available");\n')
   of.write('    document.getElementById("Earth").checked = true;\n')
   of.write('    SolarSystemObject = "P/Earth/BlueMarble";\n')
   of.write('  }\n')
   of.write('};\n')
   of.write('</script>\n')
   of.write('<script type="text/javascript" src="https://aladin.u-strasbg.fr/AladinLite/api/v2/latest/aladin.min.js" charset="utf-8"></script>\n')
   of.write('<table><tr valign="top"><td>\n')
   of.write('<div id="aladin-lite-div" style="width:80vw; height:95vh;">\n')
   of.write('  <div id="al"></div>\n')
   of.write('  <a href="https://firmamento.nyuad.nyu.edu" target="_blank" rel="noopener noreferrer">\n')
   of.write('  <img\n')
   of.write('    src="https://firmamento.nyuad.nyu.edu/static/media/firmamento_logo_orange.png"\n')
   of.write('    id="custom-logo"\n')
   of.write('    alt="Firmamento logo"\n')
   of.write('    title="Firmamento logo">\n')
   of.write('   </a>\n')
   of.write('  </div>\n')
   of.write('</td><td style="background-color: #ebfafaff"><sm> <div style="width:18vw;">\n')
   of.write('<b><br><center>The Solar system</center></b>\n')
   of.write('<input id="Sun" type="radio"   name="survey" value="CDS/P/Sun/euvi-aia304-2012"><label for="Sun">The Sun</label><br><br>\n' )
   of.write("<center><strong>The Earrth and its moon (1 of 1)</strong></center><br>\n" )
   of.write('<input id="Earth" type="radio"   name="survey" value="P/Earth/BlueMarble" checked="checked"><label for="Earth">Earth</label>\n' )
   of.write('<input id="EarthElevation" type="radio"   name="survey" value="P/Earth/DEM/elevation"><label for="EarthElevation">Earth elevation</label><br>\n' )
   of.write('<input id="Moon" type="radio"   name="survey" value="P/Moon/LROC-WAC-100m"><label for="Moon">The Moon</label>\n' )
   of.write('<input id="MoonChange2" type="radio"   name="survey" value="China-VO/P/Change2/moon/7m/DOM"><label for="MoonChange2">The Moon (Chang-E2)</label><br>\n' )
   of.write('<input id="Moon_Geo" type="radio"   name="survey" value="P/Moon/geological-map"><label for="Moon_geo">Moon Geological map</label><br>\n' )
   of.write("<center><strong>Mercury (no moons)</strong></center><br>\n" )
   of.write('<input id="Mercury" type="radio"   name="survey" value="P/Mercury/MESSENGER-MDIS-LOI-166m"><label for="Mercury">Mercury</label><br>\n' )
   of.write("<center><strong>Venus (no moons)</strong></center><br>\n" )
   of.write('<input id="Venus" type="radio"   name="survey" value="P/Venus/Magellan/Topography-4641m"><label for="Venus">Venus</label><br>\n' )
   of.write("<center><strong>Mars and its moons (0 of 2) </strong></center><br>\n" )
   of.write('<input id="Mars" type="radio"   name="survey" value="P/Mars/MOLA-color"><label for="Mars">Mars</label>\n' )
   of.write('<input id="MarsThemis" type="radio"   name="survey" value="P/Mars/THEMIS-Day-100m-v12"><label for="MarsThemis">Mars (Themis-100m)</label><br>\n' )
   of.write("<center><strong>Ceres dwarf planet</strong></center>\n" )
   of.write('<input id="Ceres" type="radio"   name="survey" value="IAPS_P_Ceres_Dawn_FC-CE-LAMO-CLR"><label for="Ceres">Ceres</label><br><br>\n' )
   of.write("<center><strong>Jupiter and its moons (4 of 95)</strong></center><br>\n" )
   of.write('<input id="Jupiter" type="radio"   name="survey" value="P/Jupiter/PIA07782"><label for="Jupiter">Jupiter</label><br>\n' )
   of.write('<input id="Io" type="radio"   name="survey" value="P/Io/Galileo-SSI-1km"><label for="Io">Io</label>\n' )
   of.write('<input id="Callisto" type="radio"   name="survey" value="P/Callisto/Voyager-Galileo-simp-1km"><label for="Callisto">Callisto</label><br>\n' )
   of.write('<input id="Ganymede" type="radio"   name="survey" value="P/Ganymede/VoyagerGalileo-SSI-1km"><label for="Ganymede">Ganymede</label>\n' )
   of.write('<input id="Europa" type="radio"   name="survey" value="P/Europa/Voyager-GalileoSSI-500m"><label for="Europa">Europa</label><br><br>\n' )
   of.write("<center><strong>Saturn and its moons (6 of 145)</strong></center><br>\n" )
   of.write('<input id="Saturn" type="radio"   name="survey" value="" disabled><label for="Saturn">Saturn (not yet available)</label><br>\n' )
   of.write('<input id="Dione" type="radio"   name="survey" value="P/Dione/Cassini-PIA12577"><label for="Dione">Dione (Cassini)</label>\n' )
   of.write('<input id="Lapetus" type="radio"   name="survey" value="P/Iapetus/Cassini-PIA18436"><label for="Lapetus">Lapetus (Cassini)</label><br>\n' )
   of.write('<input id="Mimas" type="radio"   name="survey" value="P/Mimas/Cassini-PIA17214"><label for="Mimas">Mimas (Cassini)</label>\n' )
   of.write('<input id="Rhea" type="radio"   name="survey" value="P/Rhea/Cassini-PIA12803"><label for="Rhea">Rhea (Cassini/Voyager)</label><br>\n' )
   of.write('<input id="Titan" type="radio"   name="survey" value="P/Titan/ISS-P19658-4km"><label for="Titan">Titan (Cassini)</label>\n' )
   of.write('<input id="Tethys" type="radio"   name="survey" value="P/Tethys/Cassini-PIA18439"><label for="Tethys">Tethys (Cassini)</label><br><br>\n' )
   of.write("<center><strong>Uranus and its moons (5 of 27)</strong></center><br>\n" )
   of.write('<input id="Uranus" type="radio"   name="survey" value="" disabled><label for="Uranus">Uranus (not yet available)</label><br>\n' )
   of.write('<input id="Titania" type="radio"   name="survey" value="P/Titania/Voyager"><label for="Titania">Titania (Voyager)</label>\n' )
   of.write('<input id="Ariel" type="radio"   name="survey" value="P/Ariel/Voyager"><label for="Ariel">Ariel</label><br>\n' )
   of.write('<input id="Miranda" type="radio"   name="survey" value="P/Miranda/Voyager"><label for="Miranda">Miranda</label>\n' )
   of.write('<input id="Oberon" type="radio"   name="survey" value="P/Oberon/Voyager"><label for="Oberon">Oberon</label>\n' )
   of.write('<input id="Umbriel" type="radio"   name="survey" value="P/Umbriel/Voyager"><label for="Umbriel">Umbriel</label><br><br>\n' )
   of.write("<center><strong>Neptune and its moons (1 of 14)</strong></center><br>\n" )
   of.write('<input id="Neptune" type="radio"   name="survey" value="P/Neptune/Voyager2"><label for="Neptune">Neptune (Voyager2)</label><br>\n' )
   of.write('<input id="Triton" type="radio"   name="survey" value="P/Triton/Voyager2-600m"><label for="Triton">Triton (Voyager2)</label><br><br>\n' )
   of.write("<center><strong>Pluto and its moons (1 of 5) </strong></center><br>\n" )
   of.write('<input id="Pluto" type="radio"   name="survey" value="P/Pluto/NewHorizons-Jul2017-300m"><label for="Pluto">Pluto</label><br>\n' )
   of.write('<input id="Charon" type="radio"   name="survey" value="P/Charon/NewHorizon-PIA19866"><label for="Charon">Charon</label><br>\n' )

   of.write('<!-- Modal -->\n')
   of.write('<div id="myModal" class="modal">\n')
   of.write('  <div class="modal-content">\n')
   of.write('    <span class="close-btn">&times;</span>\n')
   of.write('    <iframe id="surveyFrame" src=""></iframe>\n')
   of.write('  </div>\n')
   of.write('</div> \n')
   of.write('<img\n')
   of.write('  src="http://localhost:8080/Fbook/logo/firmamento_logo_questions.png"\n')
   of.write('  id="custom-logo3"\n')
   of.write('  alt="Questions about the cosmos"\n')
   of.write('  title="Questions about the cosmos"\n')
   of.write('  style="cursor: pointer;"\n')
   of.write('/> \n')
   of.write('<div id="myModal3" class="modal">\n')
   of.write('  <div class="modal-content">\n')
   of.write('    <span class="close-btn3">&times;</span>\n')
   of.write(' <iframe id="SolarSystemFrame" src=""></iframe>\n')
   of.write('  </div>\n')
   of.write('</div>\n')
   of.write('</div></sm></td></tr><tr><td> <center> \n')
   of.write('</center></td> </tr>\n')
   of.write('</table>\n')

   string = '<script type="text/javascript" src="https://aladin.cds.unistra.fr/AladinLite/api/v3/latest/aladin.js" charset="utf-8"></script>\n'
   of.write(string)
   of.write('<script type="text/javascript">\n')
   of.write('let aladin;\n')
   of.write('A.init.then(() => {\n')
   string = "   aladin = A.aladin(\"#aladin-lite-div\", {survey: 'P/Earth/BlueMarble',showSimbadPointerControl: false, fov:280.0, target:'0.0 0.0'" +"});\n\n"
   of.write(string)
   of.write('   aladin.gotoRaDec(long, lat);\n')


   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Sun_euvi-aia304-2012/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Sun/euvi-aia304-2012","Sun",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Earth_BlueMarble/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Earth/BlueMarble","Earth",hipsDir,"equatorial",5,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Earth_DEM_elevation/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Earth/DEM/elevation","EarthElevation",hipsDir,"equatorial",8,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Moon_LROC-WAC-100m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Moon/LROC-WAC-100m","Moon",hipsDir,"equatorial",3,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://hips.china-vo.org/change2-moon-7m-dom/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("China-VO/P/Change2/moon/7m/DOM","MoonChange2",hipsDir,"equatorial",9,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Moon_geological-map/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Moon/geological-map","Moon-Geo",hipsDir,"equatorial",3,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Mercury_MESSENGER-MDIS-LOI-166m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Mercury/MESSENGER-MDIS-LOI-166m","Mercury",hipsDir,"equatorial",5,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Venus_Magellan_Topography-4641m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Venus/Magellan/Topography-4641m","Venus",hipsDir,"equatorial",3,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/Mars_MOLA/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Mars/MOLA-color","Mars",hipsDir,"equatorial",5,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Mars_THEMIS-Day-100m-v12/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Mars/THEMIS-Day-100m-v12","MarsThemis",hipsDir,"equatorial",7,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/IAPS_P_Ceres_Dawn_FC-CE-LAMO-CLR/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("IAPS_P_Ceres_Dawn_FC-CE-LAMO-CLR","Ceres",hipsDir,"equatorial",5,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Jupiter_PIA07782/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Jupiter/PIA07782","Jupiter",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Io_Galileo-SSI-1km/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Io/Galileo-SSI-1km","Io",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Callisto_Voyager-Galileo-simp-1km/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Callisto/Voyager-Galileo-simp-1km","Callisto",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Ganymede_VoyagerGalileo-SSI-1km/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Ganymede/VoyagerGalileo-SSI-1km","Ganymede",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Europa_Voyager-GalileoSSI-500m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Europa/Voyager-GalileoSSI-500m","Europa",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Dione_Cassini-PIA12577/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Dione/Cassini-PIA12577","Dione",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Iapetus_Cassini-PIA18436/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Iapetus/Cassini-PIA18436","Lapetus",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Mimas_Cassini-PIA17214/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Mimas/Cassini-PIA17214","Mimas",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Rhea_Cassini-PIA12803/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Rhea/Cassini-PIA12803","Rhea",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Tethys_Cassini-PIA18439/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Tethys/Cassini-PIA18439","Tethys",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Titania_Voyager/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Titania/Voyager","Titania",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Miranda_Voyager/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Miranda/Voyager","Miranda",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Ariel_Voyager/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Ariel/Voyager","Ariel",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Oberon_Voyager/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Oberon/Voyager","Oberon",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Umbriel_Voyager/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Umbriel/Voyager","Umbriel",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Neptune_Voyager2/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Neptune/Voyager2","Neptune",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Triton_Voyager2-600m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Triton/Voyager2-600m","Triton",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS/P/Titan/ISS-P19658-4km/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Titan/ISS-P19658-4km","Titan",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Pluto_NewHorizons-Jul2017-300m/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Pluto/NewHorizons-Jul2017-300m","Pluto",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/Planets/CDS_P_Charon_NewHorizon-PIA19866/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("P/Charon/NewHorizon-PIA19866","Charon",hipsDir,"equatorial",3,{imgFormat:"jpeg"}));\n')

   #of.write("   aladin.setBaseImageLayer('P/Earth/BlueMarble');\n")
   of.write("   aladin.setBaseImageLayer(SolarSystemObject);\n")
   of.write('});\n')
   of.write('   $("input[name=survey]").change(function() {\n')
   of.write('      aladin.setBaseImageLayer($(this).val());\n')
   of.write('   });\n')
   of.write('</script>\n')
   of.write('<script>\n')
   of.write('//  another button\n')
   of.write(' const modal3 = document.getElementById("myModal3");\n')
   of.write(' const iframe3 = document.getElementById("SolarSystemFrame");\n')
   of.write(' const imageButton3 = document.getElementById("custom-logo3");\n')
   of.write(' imageButton3.addEventListener("click", function() {\n')
   of.write('   iframe3.src = "http://localhost:8080/Fbook/firmamento-ai-SolarSystem.html";\n')
   of.write('   modal3.style.display = "flex";\n')
   of.write(' }); \n')
   of.write(' // Close button in modal\n')
   of.write(' document.querySelector(".close-btn3").addEventListener("click", function() {\n')
   of.write('   iframe3.src = "";\n')
   of.write('   modal3.style.display = "none";\n')
   of.write(' });\n')
   of.write(' // Close modal by clicking outside modal content\n')
   of.write(' document.getElementById("myModal3").addEventListener("click", function(e) {\n')
   of.write('   if (e.target === this) {\n')
   of.write('     iframe3.src = "";\n')
   of.write('     this.style.display = "none";\n')
   of.write('   }\n')
   of.write(' });\n')
   of.write('</script>\n')

   of.write('<script type="text/javascript">\n')
   of.write('document.getElementById("hipsBase").innerHTML=hips\n')
   of.write('</script>\n')
   of.write('</HTML>\n')
