import os
import csv
#import argparse
import re
import math

ok = True
a1 = "'"
a2 = "}"
a0 = "{"

ra = 20.0
dec = 10.0
sra = (format(ra,"10.4f"))
sdec = (format(dec,"10.4f"))
output_file = 'aladin_astronomy.html'
open(output_file, 'w').close()
with open(output_file, 'w') as of:
   of.write('<HTML style="background-color:#ffffff">\n')
   of.write('<style>\n')
   of.write('sm {\n')
   of.write('  font-size: 10px;\n')
   of.write(' }\n')
   of.write('.title {\n')
   of.write('  font-size: 13px;\n')
   of.write(' }\n')
   of.write('body {\n')
   of.write(' font-family: Tahoma, sans-serif;\n')
   of.write(' margin:0;\n')
   of.write(' padding:0;\n')
   of.write('}\n')
   of.write('#custom-logo {\n')
   of.write('   position: relative;\n')
   of.write('   top: 162px;\n')
   of.write('   left: 2px;\n')
   of.write('   width: 36px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('#custom-logo2 {\n')
   of.write('   position: fixed;\n')
   of.write('   top: 15px;\n')
   of.write('   left: 92%;\n')
   of.write('   width: 50px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('#custom-logo3 {\n')
   of.write('   position: fixed;\n')
   of.write('   top: 200px;\n')
   of.write('   left: 2px;\n')
   of.write('   width: 43px;\n')
   of.write('   height: auto;\n')
   of.write('   z-index: 1000;\n')
   of.write('}\n')
   of.write('/* Modal Styling */\n')
   of.write('.info_modal {\n')
   of.write('   display: none;\n')
   of.write('   position: fixed;\n')
   of.write('   bottom: 110px;\n')
   of.write('   left: 10px;\n')
   of.write('   width: 30%;\n')
   of.write('   height: 55%;\n')
   of.write('   background: rgba(0, 0, 0, 0.0);\n')
   of.write('   justify-content: center;\n')
   of.write('   align-items: center;\n')
   of.write('   z-index: 1000;\n')
   of.write('   }\n')
   of.write('.info_modal-content {\n')
   of.write('   background-color: rgba(255, 255, 255, 0.); /* translucent white */\n')
   of.write('      padding: 0;\n')
   of.write('      border-radius: 0px;\n')
   of.write('      width: 100%;\n')
   of.write('      height: 100%;\n')
   of.write('      max-width: 900px;\n')
   of.write('      max-height: 600px;\n')
   of.write('      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.0);\n')
   of.write('      display: flex;\n')
   of.write('      flex-direction: column;\n')
   of.write('      color: #ffffff;\n')
   of.write('}\n')
   of.write('.source_modal {\n')
   of.write('   display: none;\n')
   of.write('   position: fixed;\n')
   of.write('   bottom: 120px;\n')
   of.write('   left: 190px;\n')
   of.write('   width: 90%;\n')
   of.write('   height: 3%;\n')
   of.write('   background: rgba(0, 0, 0, 0.0);\n')
   of.write('   justify-content: center;\n')
   of.write('   align-items: center;\n')
   of.write('   z-index: 1000;\n')
   of.write('   }\n')
   of.write('.source_modal-content {\n')
   of.write('   background-color: rgba(255, 255, 255, 0.); /* translucent white */\n')
   of.write('      border: 0px dotted white;\n')
   of.write('      padding: 0;\n')
   of.write('      border-radius: 0px;\n')
   of.write('      width: 100%;\n')
   of.write('      height: 100%;\n')
   of.write('      max-width: 1000px;\n')
   of.write('      max-height: 50px;\n')
   of.write('      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.0);\n')
   of.write('      display: flex;\n')
   of.write('      flex-direction: column;\n')
   of.write('      color: #ffffff;\n')
   of.write('}\n')
   of.write('.modal2 {\n')
   of.write('   display: none;\n')
   of.write('   position: fixed;\n')
   of.write('   bottom: 150px;\n')
   of.write('   left: 180px;\n')
   of.write('   width: 55%;\n')
   of.write('   height: 65%;\n')
   of.write('   background: rgba(0, 0, 0, 0.6);\n')
   of.write('   justify-content: center;\n')
   of.write('   align-items: center;\n')
   of.write('   z-index: 1000;\n')
   of.write('   }\n')
   of.write('.modal2-content {\n')
   of.write('   background-color: rgba(255, 255, 255, 0.8);\n')
   of.write('      padding: 0;\n')
   of.write('      border-radius: 0px;\n')
   of.write('      width: 100%;\n')
   of.write('      height: 100%;\n')
   of.write('      max-width: 900px;\n')
   of.write('      max-height: 600px;\n')
   of.write('      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.0);\n')
   of.write('      display: flex;\n')
   of.write('      flex-direction: column;\n')
   of.write('      color: #333;\n')
   of.write('}\n')
   of.write('.close-btn {\n')
   of.write('      align-self: flex-end;\n')
   of.write('      cursor: pointer;\n')
   of.write('      font-size: 24px;\n')
   of.write('      margin: 10px;\n')
   of.write('}\n')
   of.write('.close-btn3 {\n')
   of.write('     align-self: flex-end;\n')
   of.write('     cursor: pointer;\n')
   of.write('     font-size: 24px;\n')
   of.write('     margin: 10px;\n')
   of.write('}\n')
   of.write('iframe {\n')
   of.write('      flex: 1;\n')
   of.write('      border: none;\n')
   of.write('      border-radius: 0 0 8px 8px;\n')
   of.write('}\n')
   of.write('    body {\n')
   of.write("      font-family: 'Helvetica', sans-serif;\n")
   of.write('    }\n')
   of.write('</style>\n')
   of.write('<HEAD>\n')
   of.write('   <script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js" charset="utf-8"></script>\n')
   of.write('   <script type="text/javascript">var jqMenu = jQuery.noConflict();</script>\n')
   of.write('   <script type="text/javascript">\n')
   of.write('   var hipsDir=null;</script>\n')
   of.write('</HEAD>\n')
   of.write('<script>\n')
   of.write('const ROOT_URL = window.location.hostname.includes("localhost")\n')
   of.write('   ? "http://localhost:5000"\n')
   of.write('   : "https://firmamento.nyuad.nyu.edu";\n')
   of.write('let requestedSurvey = null;\n')
   of.write('let ra = null;\n')
   of.write('let dec = null;\n')
   of.write('let fovValue = null;\n')
   of.write('let currentSource = null;\n')
   of.write('let currentSurvey = null;\n')
   of.write('let currentHtml = null;\n')
   of.write('let item = null;\n')
   of.write('let language = "English";\n')
   of.write('window.onload = () => {\n')
   of.write('  const urlParams = new URLSearchParams(window.location.search);\n')
   of.write("  requestedSurvey = urlParams.get('survey') || 'DSS2';  \n")
   of.write("  ra = urlParams.get('ra') || '0.0';  \n")
   of.write("  dec = urlParams.get('dec') || '0.0';  \n")
   of.write("  fovValue = urlParams.get('fov') || '1.0';  \n")
   of.write("  currentHtml = urlParams.get('html') || 'details.html';  \n")
   of.write("  currentSource = urlParams.get('source') || '?';  \n")
   of.write("  language = urlParams.get('lang') || '?';\n")
   of.write("  item = urlParams.get('item') || '?';\n")
   of.write('  if (requestedSurvey == "DSS2") {\n')
   of.write('    document.getElementById("DSS2").checked = true;\n')
   of.write('    currentSurvey = "P/DSS2/color";\n')
   of.write('  } else if (requestedSurvey == "unWISE") {\n')
   of.write('    document.getElementById("unWISE").checked = true;\n')
   of.write('    currentSurvey = "unWISE";\n')
   of.write('  } else if (requestedSurvey == "JWST/F200W") {\n')
   of.write('    document.getElementById("JWST/F200W").checked = true;\n')
   of.write('    currentSurvey = "P/JWST/F200W";\n')
   of.write('  } else if (requestedSurvey == "allWISE") {\n')
   of.write('    document.getElementById("allwise").checked = true;\n')
   of.write('    currentSurvey = "P/allWISE/color";\n')
   of.write('  } else if (requestedSurvey == "PanSTARRS") {\n')
   of.write('    document.getElementById("PANSTARRS").checked = true;\n')
   of.write('    currentSurvey = "P/PanSTARRS/DR1/color-z-zg-g";\n')
   of.write('  } else if (requestedSurvey == "RASS") {\n')
   of.write('    document.getElementById("RASS").checked = true;\n')
   of.write('    currentSurvey = "P/RASS";\n')
   of.write('  } else if (requestedSurvey == "XMM-EPIC") {\n')
   of.write('    document.getElementById("XMM-EPIC").checked = true;\n')
   of.write('    currentSurvey = "XMM/EPIC-RGB";\n')
   of.write('  } else if (requestedSurvey == "GALEXGR6_7") {\n')
   of.write('    document.getElementById("GALEXGR6_7").checked = true;\n')
   of.write('    currentSurvey = "GALEXGR6_7";\n')
   of.write('  } else if (requestedSurvey == "DESI") {\n')
   of.write('    document.getElementById("DESI").checked = true;\n')
   of.write('    currentSurvey = "P/DESI-Legacy-Surveys/DR10/i";\n')
   of.write('  } else if (requestedSurvey == "SDSS9") {\n')
   of.write('    document.getElementById("SDSS9").checked = true;\n')
   of.write('    currentSurvey = "P/SDSS9/color";\n')
   of.write('  } else if (requestedSurvey == "Chandra") {\n')
   of.write('    document.getElementById("Chandra").checked = true;\n')
   of.write('    currentSurvey = "Chandra color";\n')
   of.write('  } else if (requestedSurvey == "ZTF") {\n')
   of.write('    document.getElementById("ZTF").checked = true;\n')
   of.write('    currentSurvey = "ZTF/DR7/color";\n')
   of.write('  } else if (requestedSurvey == "2MASS") {\n')
   of.write('    document.getElementById("2MASS").checked = true;\n')
   of.write('    currentSurvey = "P/2MASS/color";\n')
   of.write('  } else if (requestedSurvey == "Fermi-LAT") {\n')
   of.write('    document.getElementById("Fermi-LAT").checked = true;\n')
   of.write('    currentSurvey = "P/Fermi/color";\n')
   of.write('  } else if (requestedSurvey == "constellations") {\n')
   of.write('    document.getElementById("CONSTELLATIONS3").checked = true;\n')
   of.write('    currentSurvey = "CONSTELLATIONS3";\n')
   of.write('  } else if (requestedSurvey == "NVSS") {\n')
   of.write('    document.getElementById("NVSS").checked = true;\n')
   of.write('    currentSurvey = "NVSS";\n')
   of.write('  } else {\n')
   of.write('//    alert("Data for Survey " + requestedSurvey + " not available");\n')
   of.write('    document.getElementById("DSS2").checked = true;\n')
   of.write('    currentSurvey = "P/DSS2/color";\n')
   of.write('  }\n')
   of.write('//  alert("currentSurvey " + currentSurvey + " ra " + ra + " dec " + dec); \n')
   of.write('};\n')
   of.write('</script>\n')
   of.write('<script type="text/javascript" src="https://aladin.u-strasbg.fr/AladinLite/api/v2/latest/aladin.min.js" charset="utf-8"></script>\n')
   #of.write("<legend class='title'>SED error regions map for<sub><sub><sub>\n")
   #of.write('<img class="logoImg" src="https://vouwebsite.web.app/blackLogo.png" alt="LOGO" width="100" height="30"></sub></sub></sub>&emsp;Based on "Aladin Lite" developed at CDS, Strasbourg Observatory, France<br></legend>\n')
   of.write('<table><tr valign="top"><td>\n')
   of.write('<div id="aladin-lite-div" style="width:80vw; height:95vh;">\n')
   of.write('  <div id="al"></div>\n')
   of.write('  <a href="https://firmamento.nyuad.nyu.edu" target="_blank" rel="noopener noreferrer">\n')
   of.write('  <img\n')
   of.write('    src="https://firmamento.nyuad.nyu.edu/static/media/firmamento_logo_orange.png"\n')
   of.write('    id="custom-logo"\n')
   of.write('    alt="Firmamento logo"\n')
   of.write('    title="Firmamento logo">\n')
   of.write('   </a>\n')
   of.write('  </div>\n')
   of.write('</td><td style="background-color: #ebfafaff"><sm> <div style="width:18vw;">\n')
   of.write('<b><center>Radio surveys</center></b>\n')
   if dec < -40: 
      of.write('<input id="SUMSS" type="radio"   name="survey" value="SUMSS"><label for="SUMSS">SUMSS</label><br>\n')
      if dec > -53: 
         of.write('<input id="TGSSADR" type="radio"   name="survey" value="TGSSADR"><label for="TGSSADR">TGSSADR (150 MHz)</label><br>\n')
   else:
      of.write('<input id="NVSS" type="radio"   name="survey" value="NVSS"><label for="NVSS">NVSS (1.4 GHz)</label><br>\n' )
      of.write('--&nbsp;&nbsp;&nbsp;<b>VLASS</b> (3GHz)&nbsp;&nbsp;&nbsp;--<br>\n')
      of.write('<input id="VLASS_Epoch1" type="radio"   name="survey" value="VLASS_Epoch1"><label for="VLASS_Epoch1">Epoch 1</label>\n' )
      of.write('<input id="VLASS2.2" type="radio"   name="survey" value="VLASS2.2"><label for="VLASS2.2">2.2</label>\n' )
      of.write('<input id="VLASS3.1" type="radio"   name="survey" value="VLASS3.1"><label for="VLASS3.1">3.1</label><br>\n' )
      of.write('<input id="VCSS1" type="radio"   name="survey" value="VCSS1"><label for="VCSS1">VCSS1 (340 MHz)</label><br>\n' )
      of.write('<input id="TGSSADR" type="radio"   name="survey" value="TGSSADR"><label for="TGSSADR">TGSSADR (150 MHz)</label><br>\n')
   if dec < 8: 
      of.write('<input id="EMU" type="radio"   name="survey" value="EMU"><label for="EMU">EMU 943 MHz</label><br>\n')
   if dec < 41: 
      of.write('--&nbsp;&nbsp;&nbsp;<b>RACS</b>&nbsp;&nbsp;&nbsp;--<br>\n')
   if dec < 40: 
      of.write('<input id="RACS-low" type="radio"   name="survey" value="RACS-low"><label for="RACS-low">Low-887 MHz</label>\n')
   if dec < 49: 
      of.write('<input id="RACS-mid" type="radio"   name="survey" value="RACS-mid"><label for="RACS-mid">Mid-1367 MHz</label><br>\n')
   if dec < 48: 
      of.write('<input id="RACS-high" type="radio"   name="survey" value="RACS-high"><label for="RACS-high">High-1655 MHz</label><br>\n')
   of.write('<b><center>IR surveys</center></b>\n')
#   of.write('<br><b><center>IR surveys</center></b><br>\n')
   of.write('<input id="allwise" type="radio"   name="survey" value="P/allWISE/color"><label for="allwise">AllWISE</label><br>\n')
   of.write('<input id="unWISE"  type="radio"   name="survey" value="unWISE"><label for="unWISE">unWISE color</label><br>\n')

   of.write('<input id="2MASS" type="radio"   name="survey" value="P/2MASS/color"><label for="2MASS">2MASS</label><br>\n')
   of.write('<input id="Spitzer/IRAC134" type="radio"   name="survey" value="Spitzer/IRAC134"><label for="Spitzer/IRAC134">Spitzer/IRAC134</label><br>\n')
   of.write('<input id="Herschel/color" type="radio" name="survey" value="Herschel/color"><label for="Herschel/color">Herschel/color</label><br>\n')
   of.write('<input id="JWST/OPEN" type="radio" name="survey" value="P/JWST/OPEN"><label for="JWST/OPEN">JWST/OPEN</label>\n')
   of.write('<input id="JWST/F200W" type="radio" name="survey" value="P/JWST/F200W"><label for="JWST/F200W">JWST/F200W</label><br>\n')
   if dec < 2:
      of.write('<input id="DENIS" type="radio"   name="survey" value="P/DENIS/I"><label for="DENIS-I">DENIS-I</label><br>\n')
   of.write('<b><center>OpticalUV surveys</center></b>\n')

   if dec > -30:
      of.write('<input id="DSS2" type="radio"   name="survey" value="P/DSS2/color"><label for="DSS2">DSS2</label><br>\n')
      of.write('<input id="PANSTARRS" type="radio"   name="survey" value="P/PanSTARRS/DR1/color-z-zg-g"  checked="checked"><label for="P/PanSTARRS/DR1/color">PanSTARRS-DR1</label><br>\n')
   else:
      of.write('<input id="DSS2" type="radio"   name="survey" value="P/DSS2/color" checked="checked"><label for="DSS2">DSS2</label><br>\n')
      of.write('<input id="DES-DR2" type="radio"   name="survey" value="DES/DR2/CDS_P_DES-DR2_ColorIRG"><label for="DES-DR2">DES-DR2</label><br>\n')
   if dec < 30.:
      of.write('<input id="DESI" type="radio"   name="survey" value="P/DESI-Legacy-Surveys/DR10/i"><label for="DESI">DESI Legacy Surveys</label>\n')
   if dec > -8:
      of.write('<input id="SDSS9" type="radio"   name="survey" value="P/SDSS9/color"><label for="SDSS9">SDSS9</label><br>\n')
   if ( (dec < 35 ) & ( dec > -10 ) ) & ( ( ra > 100 ) & ( ra < 280 ) ): 
      of.write('<input id="DECaLS/DR5/color"   type="radio" name="survey" value="DECaLS/DR5/color"><label for="DECaLS-DR5">DECaLS-DR5</label><br>\n')
   if ( dec > 30 ) & ( ( ra > 100 ) & (ra < 280 ) ):
      of.write('<input id="BASS/DR3/image"   type="radio" name="survey" value="BASS/DR3/image"><label for="BASS/DR3">BASS-DR3</label><br>\n')
   if dec > -28: 
      of.write('<input id="ZTF"   type="radio" name="survey" value="ZTF/DR7/color"><label for="ZTF/DR7/color">ZTF-DR7</label><br>\n')
   if ( dec < 2 ) & ( dec > -30 ): 
      of.write('<input id="MAMA color"   type="radio" name="survey" value="MAMA color"><label for="MAMA color">MAMA</label><br>\n')
   if dec < 0 : 
      of.write('<br><input id="SkyMapper" type="radio"   name="survey" value="SkyMapper"><label for="Skymapper">SkyMapper-DR1</label><br>\n')
   of.write('<input id="EUCLIDQ1" type="radio"   name="survey" value="P/Euclid/Q1/color"><label for="EUCLIDQ1">EUCLID-Q1</label><br>\n')
   of.write('<input id="GALEXGR6_7" type="radio"  name="survey" value="GALEXGR6_7"><label for="GALEXGR6_7">GALEXGR6_7</label><br>\n')
   of.write('--&nbsp;&nbsp;&nbsp;<b>Swift-UVOT</b>&nbsp;&nbsp;&nbsp;--<br>\n')
   of.write('<input id="Swift-UVOT-M2" type="radio"  name="survey" value="Swift-UVOT-M2"><label for="Swift-UVOT-M2">M2</label>\n')
   of.write('<input id="Swift-UVOT-W1" type="radio"  name="survey" value="Swift-UVOT-W1"><label for="Swift-UVOT-W1">W1</label>\n')
   of.write('<input id="Swift-UVOT-W2" type="radio"  name="survey" value="Swift-UVOT-W2"><label for="Swift-UVOT-W2">W2</label><br>\n')

   of.write('<b><center>X-ray/&gamma;-ray surveys</center></b>\n ')
   of.write('--&nbsp;&nbsp;&nbsp;<b>eRASS1</b>&nbsp;&nbsp;&nbsp;--<br>\n')
   of.write('<input id="eRosita" type="radio"  name="survey" value="eRASS1_RGB_Rate_c010"><label for="eROSITA-RGB">Color</label>\n')
   of.write('<input id="eRosita" type="radio"  name="survey" value="eRASS1_024_Rate_c010"><label for="eROSITA-024">0.2-2.3 keV</label>\n')
   of.write('<input id="eRosita" type="radio"  name="survey" value="eRASS1_023_Rate_c010"><label for="eROSITA-023">2.3-5 keV</label><br>\n')
   #of.write('<input id="Swift-XRT" type="radio"  name="survey" value="Swift/XRT/OpenUniverse color"><label for="Swift-XRT">Swift-XRT</label>\n')
   of.write('<input id="Swift-BAT" type="radio"  name="survey" value="Swift-BAT"><label for="Swift-BAT">Swift-BAT(14-20keV)</label><br>\n')
   of.write('<input id="XMM-PN" type="radio"  name="survey" value="XMM/PN/color"><label for="XMM/PN/color">XMM-PN</label>\n')
   of.write('<input id="XMM-EPIC" type="radio"  name="survey" value="XMM/EPIC-RGB"><label for="XMM/EPIC-RGB">XMM-EPIC</label><br>\n')
   of.write('<input id="Chandra" type="radio"  name="survey" value="Chandra color"><label for="Chandra color">Chandra</label><br>\n')
   of.write('<input id="RASS" type="radio"  name="survey" value="P/RASS"><label for="P/RASS">RASS</label><br>\n')
   of.write('<input id="MAXI-GSC" type="radio"  name="survey" value="MAXI-GSC"><label for="MAXI-GSC">MAXI-GSC</label><br>\n')
   of.write('<input id="Fermi-LAT" type="radio"  name="survey" value="P/Fermi/color"><label for="P/Fermi/color">Fermi-LAT</label><br>\n')
   of.write('<input id="TestSwift" type="radio"  name="survey" value="OU/P/SwiftXRT"><label for="TestSwift"><font color=red>Swift-XRT</font></label>\n')
   of.write('<input id="Swift-Col" type="radio"  name="survey" value="OU/P/SwiftXRT-color"><label for="Swift-Col"><font color=red>Swift-XRT color</font></label><br>\n')
   of.write('<input id="TestNuSTAR" type="radio"  name="survey" value="FIRMAMENTO/P/NuSTAR"><label for="TestNuSTAR"><font color=red>NuSTAR</font></label>\n')

   of.write('<!-- Image acting as a button -->\n')
   of.write('<img\n')
   of.write('  src="http://localhost:5000/Fbook/logo/firmamento_logo_help.png"\n')
   of.write('  id="custom-logo2"\n')
   of.write('  alt="Show surveys description page"\n')
   of.write('  title="Surveys description page"\n')
   of.write('  style="cursor: pointer;"\n')
   of.write('/>\n')
   of.write('<!-- Modal -->\n')
   of.write('<div id="myModal" class="modal2">\n')
   of.write('  <div class="modal2-content">\n')
   of.write('    <span class="close-btn">&times;</span>\n')
   of.write('    <iframe id="surveyFrame" src=""></iframe>\n')
   of.write('  </div>\n')
   of.write('</div> \n')
   of.write('<img\n')
   of.write('  src="http://localhost:5000/Fbook/logo/F-logo-info.png"\n')
   of.write('  id="custom-logo3"\n')
   of.write('  alt="Source information button"\n')
   of.write('  title="Source information button"\n')
   of.write('  style="cursor: pointer;"\n')
   of.write('/> \n')
   of.write('<div id="myModal3" class="info_modal">\n')
   of.write('  <div class="info_modal-content">\n')
   of.write('    <span class="close-btn3">&times;</span>\n')
   of.write(' <iframe id="questionsFrame" src=""></iframe>\n')
   of.write('  </div>\n')
   of.write('</div>\n')
   of.write('<div id="myModalS" class="source_modal">\n')
   of.write('  <div class="source_modal-content">\n')
   of.write('    <span class="close-btn3">&times;</span>\n')
   of.write(' <iframe id="sourceFrame" src=""></iframe>\n')
   of.write('  </div>\n')
   of.write('</div>\n')
   of.write('</div></sm></td></tr><tr><td> <center> \n')
   of.write('<input id="CONSTELLATIONS3" type="radio"  name="survey" value="CONSTELLATIONS3"><label for="Constellations">Constellations</label>\n')
   of.write('</center></td> </tr>\n')
   of.write('</table>\n')

   string = '<script type="text/javascript" src="https://aladin.cds.unistra.fr/AladinLite/api/v3/latest/aladin.js" charset="utf-8"></script>\n'
   of.write(string)
   of.write('<script type="text/javascript">\n')
   of.write('let aladin;\n')
   of.write('A.init.then(() => {\n')
   string = "   aladin = A.aladin(\"#aladin-lite-div\", {survey: 'P/DSS2/color',showSimbadPointerControl: 'True', fov:0.2, target:'"+sra.strip()+" "+sdec.strip()+"'});\n\n"
   of.write(string)
   of.write('   aladin.gotoRaDec(ra,dec);\n')
   of.write('   aladin.setFov(fovValue);\n')

   #of.write('   hipsDir = "https://openuniverse.asi.it/SwiftXRT4OU/outSwiftHiPS_ALLupAug2020-RGB/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   #of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift/XRT/OpenUniverse color','Swift/XRT/OpenUniverse color',hipsDir,'equatorial',7,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://erosita.mpe.mpg.de/dr1/erodat/static/hips/eRASS1_RGB_Rate_c010/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('eRASS1_RGB_Rate_c010','eRASS1_RGB_Rate_c010',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://erosita.mpe.mpg.de/dr1/erodat/static/hips/eRASS1_024_Rate_c010/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('eRASS1_024_Rate_c010','eRASS1_024_Rate_c010',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://erosita.mpe.mpg.de/dr1/erodat/static/hips/eRASS1_023_Rate_c010/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('eRASS1_023_Rate_c010','eRASS1_023_Rate_c010',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/NVSS/intensity/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('NVSS','NVSS',hipsDir,'equatorial',5,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('cubehelix')\n")

   of.write('   hipsDir = "http://localhost:5000/SwiftXRTColor/";\n')
   of.write('   //hipsDir = "https://firmamento.nyuad.nyu.edu/PilotHiPS-color/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("OU/P/SwiftXRT-color","Swift-col",hipsDir,"equatorial",8,{imgFormat:"png"}));\n')
     
   of.write('   hipsDir = "http://localhost:5000/SwiftHiPS//";\n')
   of.write('   //hipsDir = "https://firmamento.nyuad.nyu.edu/PilotHiPS/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("OU/P/SwiftXRT","TestSwift",hipsDir,"equatorial",8,{imgFormat:"png"}));\n')

   of.write('   //hipsDir = "http://localhost:5000/PilotHiPS-NuSTAR/";\n')
   of.write('   hipsDir = "http://localhost:5000/PilotHiPS-NuSTAR/";\n')
   of.write('   aladin.setImageSurvey(aladin.createImageSurvey("FIRMAMENTO/P/NuSTAR","TestNuSTAR",hipsDir,"equatorial",8,{imgFormat:"png"}));\n')

   of.write('   hipsDir = "https://www.aoc.nrao.edu/~jmarvil/emuHiPS/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('EMU','EMU',hipsDir,'equatorial',7,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://archive-new.nrao.edu/vlass/HiPS/VLASS2.2/Quicklook/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('VLASS2.2','VLASS2.2',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://archive-new.nrao.edu/vlass/HiPS/VLASS3.1/Quicklook/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('VLASS3.1','VLASS3.1',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://archive-new.nrao.edu/vlass/HiPS/VLASS_Epoch1/Quicklook/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('VLASS_Epoch1','VLASS_Epoch1',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://archive-new.nrao.edu/vlass/HiPS/VCSS1/Images_vcss1_HiPS/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('VCSS1','VCSS1',hipsDir,'equatorial',8,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://casda.csiro.au/hips/RACS/low/I/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('RACS-low','RACS-low',hipsDir,'equatorial',8,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://casda.csiro.au/hips/RACS/mid/I/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('RACS-mid','RACS-mid',hipsDir,'equatorial',8,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://www.atnf.csiro.au/research/RACS/RACShigh1_I1/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('RACS-high','RACS-high',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")
   
   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/DECaLS/DR5/color/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('DECaLS/DR5/color','DECaLS/DR5/color',hipsDir,'equatorial',11,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/DENIS/CDS_P_DENIS_I/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/DENIS/I','DENIS-I',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n") 
      
   of.write('   hipsDir = "https://alasky.cds.unistra.fr/DESI-legacy-surveys/DR10/CDS_P_DESI-Legacy-Surveys_DR10_i/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/DESI-Legacy-Surveys/DR10/i','DESI',hipsDir,'equatorial',11,{imgFormat:'png'}));\n\n") 
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/JWST/CDS_P_JWST_OPEN/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/JWST/OPEN','JWST/OPEN',hipsDir,'equatorial',14,{imgFormat:'png'}));\n\n") 
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/JWST/CDS_P_JWST_F200W/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/JWST/F200W','JWST/F200W',hipsDir,'equatorial',14,{imgFormat:'png'}));\n\n") 
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://skymapper.anu.edu.au/CDS_P_skymapper-color/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('SkyMapper','SkyMapper',hipsDir,'equatorial',9,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/CDS/P/Euclid/Q1/color";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/Euclid/Q1/color','EUCLIDQ1',hipsDir,'equatorial',13,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/RASS/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('P/RASS','RASS',hipsDir,'equatorial',4,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://erosita.mpe.mpg.de/ExposureHiPS/eRASS3/946/eROSITA_exposure_021/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('eROSITA exposure','eROSITA exposure',hipsDir,'equatorial',5,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/SUMSS/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('SUMSS','SUMSS',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://xcatdb.unistra.fr/PNColor/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('XMM/PN/color','XMM/PN/color',hipsDir,'equatorial',7,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://esdchips.esac.esa.int/XMM-Newton/EPIC-RGB/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('XMM/EPIC-RGB','XMM/EPIC-RGB',hipsDir,'equatorial',7,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/CHANDRA/cxc.harvard.edu_P_cda_hips_allsky_rgb/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Chandra color','Chandra color',hipsDir,'equatorial',11,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://data.darts.isas.jaxa.jp/pub/HiPS/MAXI-GSC_Image/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('MAXI-GSC','MAXI-GSC',hipsDir,'equatorial',3,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://data.darts.isas.jaxa.jp/pub/HiPS/SWIFT-BAT_Image/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift-BAT image','Swift-BAT image',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://cade.irap.omp.eu/documents/Ancillary/4Aladin/BAT_14_20/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift-BAT','Swift-BAT',hipsDir,'galactic',3,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('cubehelix')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/JAXA/JAXA_P_CONSTELLATIONS3/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('CONSTELLATIONS3','CONSTELLATIONS3',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/JAXA/JAXA_P_CONSTELLATIONS6/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('CONSTELLATIONS6','CONSTELLATIONS6',hipsDir,'equatorial',6,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/ZTF/DR7/CDS_P_ZTF_DR7_g/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('ZTF/DR7/color','ZTF/DR7/color',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/China-VO/China-VO_P_BASS_DR3_image/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('BASS/DR3/image','BASS/DR3/image',hipsDir,'equatorial',10,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/ESAC/ESAVO_P_HST_WFPC/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('HST/WFPC','HST/WFPC',hipsDir,'equatorial',13,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/MAMA/CDS_P_MAMA_color_posse_srcj/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('MAMA color','MAMA color',hipsDir,'equatorial',10,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/ESAC/ESAVO_P_Herschel_color/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Herschel/color','Herschel/color',hipsDir,'equatorial',8,{imgFormat:'png'}));\n\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/unWISE/color-W2-W1W2-W1/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('unWISE','unWISE',hipsDir,'equatorial',8,{imgFormat:'jpg'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://alaskybis.cds.unistra.fr/ESAC/ESAVO_P_Spitzer_IRAC134-RGB-bright/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Spitzer/IRAC134','Spitzer/IRAC134',hipsDir,'equatorial',10,{imgFormat:'png'}));\n\n")

   #of.write('   hipsDir = "http://hips.canfar.net/CDS_P_HST_wideV/";\n')
   #of.write("   aladin.newImageSurvey(hipsDir);\n")
   #of.write("   aladin.setImageSurvey(aladin.createImageSurvey('HST_wideV','HST_wideV',hipsDir,'equatorial',13,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('hipsDir = "https://hips.astron.nl/ASTRON/P/tgssadr/"; ')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('TGSSADR','TGSSADR',hipsDir,'equatorial',7,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/GALEX/GALEXGR6_7_color/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('GALEXGR6_7','GALEXGR6_7',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('rainbow')\n")

   of.write('   hipsDir = "https://alasky.cds.unistra.fr/DES/DR2/CDS_P_DES-DR2_ColorIRG/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('DES/DR2/CDS_P_DES-DR2_ColorIRG','DES-DR2',hipsDir,'equatorial',11,{imgFormat:'png'}));\n\n")

   of.write('   hipsDir = "https://skyview.gsfc.nasa.gov/surveys/uvot/cnt/UVM2/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift-UVOT-M2','Swift-UVOT-M2',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")

   of.write('   hipsDir = "https://skyview.gsfc.nasa.gov/surveys/uvot/cnt/UVW1/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift-UVOT-W1','Swift-UVOT-W1',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")

   of.write('   hipsDir = "https://skyview.gsfc.nasa.gov/surveys/uvot/cnt/UVW2/";\n')
   of.write("   aladin.setImageSurvey(aladin.createImageSurvey('Swift-UVOT-W2','Swift-UVOT-W2',hipsDir,'equatorial',9,{imgFormat:'png'}));\n\n")
   #of.write("   aladin.getBaseImageLayer(hipsDir).getColorMap(hipsDir).update('native')\n")
   of.write("   aladin.setBaseImageLayer(currentSurvey);\n")

   #if dec > -30:
   #    of.write("   aladin.setBaseImageLayer('P/PanSTARRS/DR1/color-z-zg-g');\n")
   #else: 
   #    of.write("   aladin.setBaseImageLayer('P/DSS2/color');\n")
   #of.write('\n\n')
   of.write('   $("input[name=survey]").change(function() {  \n')
   of.write("         if (($(this).val() == 'NVSS')  || ($(this).val() == 'unWISE')  || ($(this).val() == 'OU/P/SwiftXRT') || ($(this).val() == 'FIRMAMENTO/P/NuSTAR')) {  \n")
   of.write("        cmap = 'eosb'; } else { cmap = 'native'; }\n")
   of.write('      aladin.setBaseImageLayer($(this).val()).setColormap(cmap);\n')
   of.write('   });\n')
   of.write('});\n')
   of.write('</script>\n')
   of.write('<script>\n')
   of.write(' const info_modal = document.getElementById("myModal");\n')
   of.write(' const source_modal = document.getElementById("myModalS");\n')
   of.write(' const iframe = document.getElementById("surveyFrame");\n')
   of.write(' const imageButton = document.getElementById("custom-logo2");\n')
   of.write(' // Click on image triggers the modal\n')
   of.write(' imageButton.addEventListener("click", function() {\n')
   of.write('   iframe.src = "Fbook/firmamento-ai-surveys.html";\n')
   of.write('   info_modal.style.display = "flex";\n')
   of.write(' }); \n')
   of.write(' // Close button in modal\n')
   of.write(' document.querySelector(".close-btn").addEventListener("click", function() {\n')
   of.write('   iframe.src = "";\n')
   of.write('   info_modal.style.display = "none";\n')
   of.write(' });\n')
   of.write(' // Close modal by clicking outside modal content\n')
   of.write(' document.getElementById("myModal").addEventListener("click", function(e) {\n')
   of.write('   if (e.target === this) {\n')
   of.write('     iframe.src = "";\n')
   of.write('     this.style.display = "none";\n')
   of.write('   }\n')
   of.write(' });\n')
   of.write('//  another button\n')
   of.write(' const modal3 = document.getElementById("myModal3");\n')
   of.write(' const iframe3 = document.getElementById("questionsFrame");\n')
   of.write(' const modal4 = document.getElementById("myModalS");\n')
   of.write(' const iframe4 = document.getElementById("sourceFrame");\n')
   of.write(' const imageButton3 = document.getElementById("custom-logo3");\n')
   of.write(' imageButton3.addEventListener("click", function() {\n')
   of.write('   iframe3.src = `${ROOT_URL}/${currentHtml}?source=${currentSource}&lang=${language}&survey=${requestedSurvey}&item=${item}`\n')
   of.write('   iframe4.src = `${ROOT_URL}/Details2.html?source=${currentSource}&lang=${language}&survey=${requestedSurvey}&item=${item}`\n')
   of.write('   modal3.style.display = "flex";\n')
   of.write('   modal4.style.display = "flex";\n')
   of.write(' }); \n')
   of.write(' // Close button in modal\n')
   of.write(' document.querySelector(".close-btn3").addEventListener("click", function() {\n')
   of.write('   iframe3.src = "";\n')
   of.write('   modal3.style.display = "none";\n')
   of.write('   iframe4.src = "";\n')
   of.write('   modal4.style.display = "none";\n')
   of.write(' });\n')
   of.write(' // Close modal by clicking outside modal content\n')
   of.write(' document.getElementById("myModal3").addEventListener("click", function(e) {\n')
   of.write('   if (e.target === this) {\n')
   of.write('     iframe3.src = "";\n')
   of.write('     this.style.display = "none";\n')
   of.write('   }\n')
   of.write(' });\n')
   of.write(' document.getElementById("myModalS").addEventListener("click", function(e) {\n')
   of.write('   if (e.target === this) {\n')
   of.write('     iframe4.src = "";\n')
   of.write('     this.style.display = "none";\n')
   of.write('   }\n')
   of.write(' });\n')
   of.write('</script>\n')

   of.write('<script type="text/javascript">\n')
   of.write('document.getElementById("hipsBase").innerHTML=hips\n')
   of.write('</script>\n')
   of.write('</HTML>\n')
